name: Deploy action

on:
  push:
    branches:
      - dev

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: pnpm install

      - name: Test action
        run: pnpm test

  build:
    needs: [lint, test]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm bundle

      - name: Remove not needed files
        run: |
          ls
          rm -rf node_modules .git

      - name: Upoad artifact
        uses: actions/upload-artifact@v3
        with:
          name: everything
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Remove what is alraedy there
        run: rm -rf *

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: everything
          path: .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: duplicate code of dev with bundled code"
          branch: main
